version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: greeting_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Fool@123#
      MYSQL_DATABASE: greeting_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pFool@123#"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: greeting_app
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/greeting_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Fool@123#
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
